name: Frontend Deployment

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read
  deployments: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: frontend

      - name: pnpm install
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "frontend/package.json"
          version: 9.11.0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install

      - name: Build
        run: |
          cd frontend
          pnpm run build

      - name: Get AWS Access Token via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/dist s3://decompiler-25spring-door-quiz.junah.dev --delete

      - name: Create CloudFront Invalidation
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }} --paths "/*"
